namespace Wiki
{
    public enum Namespace
    {
        Media = -2,
        Special = -1,
        Default = 0,
        Talk = 1,
        User = 2,
        UserTalk = 3,
        Project = 4,
        ProjectTalk = 5,
        File = 6,
        FileTalk = 7,
        MediaWiki = 8,
        MediaWikiTalk = 9,
        Template = 10,
        TemplateTalk = 11,
        Help = 12,
        HelpTalk = 13,
        Category = 14,
        CategoryTalk = 15,
        Thread = 90,
        ThreadTalk = 91,
        Summary = 92,
        SummaryTalk = 93,
        Manual = 100,
        ManualTalk = 101,
        Extension = 102,
        ExtensionTalk = 103,
        API = 104,
        APITalk = 105,
        Skin = 106,
        SkinTalk = 107,
        Data = 486,
        DataTalk = 487,
        Module = 828,
        ModuleTalk = 829,
        Translations = 1198,
        TranslationsTalk = 1199,
        Gadget = 2300,
        GadgetTalk = 2301,
        GadgetDefinition = 2302,
        GadgetDefinitionTalk = 2303,
        Topic = 2600,
    }
}